parameters:
#    lighthart_selectize.example.class: Lighthart\SelectizeBundle\Example

services:
#    lighthart_selectize.example:
#        class: %lighthart_selectize.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
